# Generated by Django 3.2.9 on 2021-11-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discounnt',
            new_name='discount',
        ),
    ]
